.include "src/config/config.inc"


;zp-vars,just a reference
.enum 0
  iterator INSTANCEOF iteratorStruct
  dimension INSTANCEOF dimensionStruct
  animation INSTANCEOF animationStruct
  oam INSTANCEOF oamStruct
  lifeform INSTANCEOF lifeformStruct
  ;this INSTANCEOF playerStruct
zpLen ds 0
.ende

;object class static flags, default properties and zero page 
.define CLASS.FLAGS OBJECT.FLAGS.Present
.define CLASS.PROPERTIES OBJECT.PROPERTIES.isLevelSortable
.define CLASS.ZP_LENGTH zpLen
.define CLASS.IMPLEMENTS interface.dimension


.def LIFEFORM.HITPOINTS 2
.export LIFEFORM.HITPOINTS

.def LIFEFORM.DIAMETER.DEFAULT 10
.export LIFEFORM.DIAMETER.DEFAULT

.def LIFEFORM.DIRECTION.LEFT ANIMATION.FLAGS.X_MIRROR
.def LIFEFORM.DIRECTION.RIGHT 0

.export LIFEFORM.DIRECTION.LEFT
.export LIFEFORM.DIRECTION.RIGHT

.def LIFEFORM.INVINCIBILITY.TIMER 9
.export LIFEFORM.INVINCIBILITY.TIMER

.def LIFEFORM.BERZERK.MAX 511
.export LIFEFORM.BERZERK.MAX

.def BERZERK.FULL LIFEFORM.BERZERK.MAX
.export BERZERK.FULL

.def LIFEFORM.THROW_INVINCIBLE.AGE 25
.export LIFEFORM.THROW_INVINCIBLE.AGE

.def LIFEFORM.OFFSCREEN.KILL 180

.def LIFEFORM.OFFSCREEN.KILL_THRESHOLD 513

.def LIFEFORM.ATTACK.BERZERK.RETURN 4

.def LIFEFORM.HIT.FREEZE 7
.export LIFEFORM.HIT.FREEZE

.def UPPERCUT.HIT.ACCEL -20

.def LIFEFORM.HIT.BERZERK.RETURN 5


.enum 0 export
  LIFEFORM.CONTROLLER.HUMAN.JOYPAD db
  LIFEFORM.CONTROLLER.HUMAN.MAIN db
  LIFEFORM.CONTROLLER.HUMAN.SIDEKICK db
  LIFEFORM.CONTROLLER.AI.ENEMY db
  LIFEFORM.CONTROLLER.AI.NPC db
  LIFEFORM.CONTROLLER.AI.SIDEKICK db
  LIFEFORM.CONTROLLER.AI.ANIMAL db
  LIFEFORM.CONTROLLER.AI.DUMMY db
  LIFEFORM.CONTROLLER.CUTSCENE db
  LIFEFORM.CONTROLLER.MAX db
.ende


.enum 0 export
  LIFEFORM.STATE.WALKING db
  LIFEFORM.STATE.JUMPING db
  LIFEFORM.STATE.FLIPPING db
  LIFEFORM.STATE.FALLING db
  LIFEFORM.STATE.WALLJUMPING db
  LIFEFORM.STATE.CLIMBING db
  LIFEFORM.STATE.DASHING db
  LIFEFORM.STATE.SLIDING db
  LIFEFORM.STATE.HURT db
  LIFEFORM.STATE.DYING db
  LIFEFORM.STATE.SUICIDE db
  LIFEFORM.STATE.PUNCHING db
  LIFEFORM.STATE.JUMPKICKING db
  LIFEFORM.STATE.UPPERCUT db
  LIFEFORM.STATE.SUPERPUNCH db
  LIFEFORM.STATE.GRABBING db
  LIFEFORM.STATE.JUMPGRABBING db
  LIFEFORM.STATE.THROWING db
  LIFEFORM.STATE.JUMPTHROWING db
  LIFEFORM.STATE.STASHING db
  LIFEFORM.STATE.JUMPSTASHING db
  LIFEFORM.STATE.GRABBED db
  LIFEFORM.STATE.THROWN db
  LIFEFORM.STATE.FLYING db
  LIFEFORM.STATE.CUSTOMANIMATION db
  LIFEFORM.STATE.WARPING db
.ende


.enum 0 export
  LIFEFORM.CONDITION.GROUNDED db
  LIFEFORM.CONDITION.AIRBORNE db
  LIFEFORM.CONDITION.ETHEREAL db
  LIFEFORM.CONDITION.FLYING db
  LIFEFORM.CONDITION.DASHING db
  LIFEFORM.CONDITION.BOUNCING db
.ende



;generic lifeform animation templates
.enum 0 export
  LIFEFORM.SPRITE_ANIMATION.ALLOCATION.DUMMY db
  LIFEFORM.SPRITE_ANIMATION.IDLE.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.IDLE.DUCK db
  LIFEFORM.SPRITE_ANIMATION.RUNNING.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.CROUCHING db
  LIFEFORM.SPRITE_ANIMATION.JUMPING.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.FLIP.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.JUMPKICK.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.FALLING.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.WALLHUGGING.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.DASHING.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.SLIDING.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.CLIMBING.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.GRAB.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.STASH.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.THROW.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.GRABBED.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.HURT.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.DIE.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.SUICIDE.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.UPPERCUT.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.PUNCH1.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.PUNCH2.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.PUNCH3.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.KICK1.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.KICK2.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.KICK3.RIGHT db
  LIFEFORM.SPRITE_ANIMATION.LENGTH ds 0
.ende

.enum 0 export
  LIFEFORM.COMMAND.SUMMON db
  LIFEFORM.COMMAND.SEND db
  LIFEFORM.COMMAND.CONDUCT db
  LIFEFORM.COMMAND.KILLCOUNT_INCREASE db
  LIFEFORM.COMMAND.GRAB db
  LIFEFORM.COMMAND.THROW db
  LIFEFORM.COMMAND.KNOCK_OUT db ;basically same as throw, just separated so that lifeforms can support either
  LIFEFORM.COMMAND.ATTACK db
  LIFEFORM.COMMAND.TALK db
  LIFEFORM.COMMAND.ORDER_ATTACK db
  LIFEFORM.COMMAND.ORDER_SHOOT db
  LIFEFORM.COMMAND.ORDER_FLEE db  
  LIFEFORM.COMMAND.INTIMIDATE db
  LIFEFORM.COMMAND.ASHAME db
  LIFEFORM.COMMAND.FLEE db
  LIFEFORM.COMMAND.FOCUS db
  LIFEFORM.COMMAND.ADD.STATS db
  LIFEFORM.COMMAND.GET.STATS.HP db
  LIFEFORM.COMMAND.GET.STATS.MISC db
  LIFEFORM.COMMAND.GET.STATS.LEVEL db
  LIFEFORM.COMMAND.GET.SCORE db
  LIFEFORM.COMMAND.GET.CONTROLLER db
  LIFEFORM.COMMAND.RECALCULATE.STATS db
  LIFEFORM.COMMAND.COMMIT db
  LIFEFORM.COMMAND.CANCEL db
  LIFEFORM.COMMAND.REST db
  LIFEFORM.COMMAND.BACKTRACK db
  LIFEFORM.COMMAND.SET_SPEED db
  LIFEFORM.COMMAND.SET_DISTANCE db
  LIFEFORM.COMMAND.BOUNCE db
  LIFEFORM.COMMAND.TOUCH db
  LIFEFORM.COMMAND.DETACH db
  LIFEFORM.COMMAND.SHAKE db
  LIFEFORM.COMMAND.GET_ITEM db
  LIFEFORM.COMMAND.ENTER db
  LIFEFORM.COMMAND.LEAVE db
  LIFEFORM.COMMAND.STAY db
  LIFEFORM.COMMAND.RESET_SCORE db
  LIFEFORM.COMMAND.ACCELERATE db
  LIFEFORM.COMMAND.JUMP db
  LIFEFORM.COMMAND.GET_CAMERA_DATA db
  LIFEFORM.COMMAND.CUTSCENE.START db
  LIFEFORM.COMMAND.CUTSCENE.END db
  LIFEFORM.COMMAND.CUTSCENE.ANIMATION_START db
  LIFEFORM.COMMAND.CUTSCENE.ANIMATION_PAUSE db
  LIFEFORM.COMMAND.CUTSCENE.ANIMATION_RESUME db
  LIFEFORM.COMMAND.CUTSCENE.GO_TO db
  LIFEFORM.COMMAND.CUTSCENE.WARP_TO db
  LIFEFORM.COMMAND.CUTSCENE.JUMP_INTO db
  LIFEFORM.COMMAND.CUTSCENE.SOUND_EFFECT db
  LIFEFORM.COMMAND.CUTSCENE.FOCUS db 
  LIFEFORM.COMMAND.CUTSCENE.DIRECTION db
  LIFEFORM.COMMAND.CUTSCENE.SET_SPEED db
  LIFEFORM.COMMAND.CUTSCENE.MAKE_DIZZY db
  LIFEFORM.COMMAND.MAINTAIN_RELATIVE_POSITION db
  LIFEFORM.COMMAND.SET_BEHAVIOR db
  LIFEFORM.COMMAND.RESTORE_HEALTH db
  LIFEFORM.COMMAND.ATTRACT db
  LIFEFORM.COMMAND.HURT db
  LIFEFORM.COMMAND.ADDSTATS db
  LIFEFORM.COMMAND.GET_PAYMENT db
  LIFEFORM.COMMAND.MAY_DIE db
  LIFEFORM.COMMAND.BERZERK_RETURN db
  SCRIPT.COMMAND.NEW_GAME db
  SCRIPT.COMMAND.CONTINUE_GAME db
  SCRIPT.COMMAND.MUSIC_PLAYER db
  SCRIPT.COMMAND.RECORDER db
  SCRIPT.COMMAND.SET_SCRIPT db
  SCRIPT.COMMAND.PLAY_SONG db
  SCRIPT.COMMAND.PRACTICE db
  SCRIPT.COMMAND.RECORD_SONG db
  SCRIPT.COMMAND.EXIT db
  LIFEFORM.COMMAND.RESET db
  LIFEFORM.COMMAND.GRAB_ME db
  LIFEFORM.COMMAND.SQUASH db
  LIFEFORM.COMMAND.CUTSCENE.MAX ds 0
.ende


.enum 0 export ;@see PROJECTILE.
  LIFEFORM.ATTACK.NORMAL db ;generic
  LIFEFORM.ATTACK.SUPER db
  LIFEFORM.ATTACK.UPPERCUT db
  LIFEFORM.ATTACK.DASH db
  LIFEFORM.ATTACK.SLIDE db
  LIFEFORM.ATTACK.THROWN db
.ende


.def LIFEFORM.INVINCIBILITY.DURATION.PLAYER 30
.def LIFEFORM.INVINCIBILITY.DURATION.ENEMY 4
.export LIFEFORM.INVINCIBILITY.DURATION.PLAYER
.export LIFEFORM.INVINCIBILITY.DURATION.ENEMY


.def LIFEFORM.ABILITIES.MOVE.RIGHT 1 << 0
.def LIFEFORM.ABILITIES.MOVE.LEFT 1 << 1
.def LIFEFORM.ABILITIES.MOVE.DOWN 1 << 2
.def LIFEFORM.ABILITIES.MOVE.UP 1 << 3
.def LIFEFORM.ABILITIES.JUMP 1 << 4
.def LIFEFORM.ABILITIES.ATTACK 1 << 5
.def LIFEFORM.ABILITIES.DASH 1 << 6
.def LIFEFORM.ABILITIES.GRABTHROW 1 << 7


.export LIFEFORM.ABILITIES.MOVE.RIGHT
.export LIFEFORM.ABILITIES.MOVE.LEFT
.export LIFEFORM.ABILITIES.MOVE.UP
.export LIFEFORM.ABILITIES.MOVE.DOWN
.export LIFEFORM.ABILITIES.JUMP
.export LIFEFORM.ABILITIES.ATTACK
.export LIFEFORM.ABILITIES.DASH
.export LIFEFORM.ABILITIES.GRABTHROW


.def LIFEFORM.SKILL.FLIP 1 << 0
.export LIFEFORM.SKILL.FLIP


.def LIFEFORM.DISTANCE.THRESHOLD.APPROACH 7
.def LIFEFORM.DISTANCE.THRESHOLD.APPROACH.CHEST 1
.def LIFEFORM.DISTANCE.THRESHOLD.ATTACK.MELEE 40
.def LIFEFORM.DISTANCE.THRESHOLD.ATTACK.LONGRANGE 80
.def LIFEFORM.DISTANCE.THRESHOLD.SEEKCOMPANION 160

.export LIFEFORM.DISTANCE.THRESHOLD.APPROACH
.export LIFEFORM.DISTANCE.THRESHOLD.APPROACH.CHEST
.export LIFEFORM.DISTANCE.THRESHOLD.ATTACK.MELEE
.export LIFEFORM.DISTANCE.THRESHOLD.ATTACK.LONGRANGE
.export LIFEFORM.DISTANCE.THRESHOLD.SEEKCOMPANION

.def LIFEFORM.PROJECTILE.TYPE %00111111
.def LIFEFORM.PROJECTILE.SUBTYPE LIFEFORM.PROJECTILE.TYPE~$ff
.export LIFEFORM.PROJECTILE.TYPE
.export LIFEFORM.PROJECTILE.SUBTYPE


.def LIFEFORM.DASH.VALID_COUNTER 15
.export LIFEFORM.DASH.VALID_COUNTER


.def LIFEFORM.COMBO.COUNT 10

.def LIFEFORM.COLLISION.PADDING 0
.export LIFEFORM.COLLISION.PADDING

.base BSL
.bank BANK.PROGRAM