.include "src/config/config.inc"

.def LIFEFORM.JUMP.IMPULSE -800
.def LIFEFORM.JUMP.ACCEL -10
.def LIFEFORM.FLIP.ACCEL -100
.def LIFEFORM.JUMP.SUSTAIN -22
.def LIFEFORM.JUMP.AGE 12

.export LIFEFORM.JUMP.IMPULSE 
.export LIFEFORM.JUMP.ACCEL 
.export LIFEFORM.JUMP.AGE

.def LIFEFORM.BOMB.POWER 9

.def LIFEFORM.WALLJUMP.IMPULSE 800
.def LIFEFORM.WALLJUMP.ACCEL 60
.def LIFEFORM.WALLJUMP.AGE 40

.def LIFEFORM.FLUTTER.SPEED 300
.def LIFEFORM.FLUTTER.ACCEL.MAX 300

.def LIFEFORM.HEAD.BOP.IMPULSE 50

.def WALLHUG.SPEED.Y 140

.def LIFEFORM.DASH.IMPULSE 1600
.def LIFEFORM.DASH.ACCEL 70
.def LIFEFORM.DASH.AGE 20

.export LIFEFORM.DASH.IMPULSE
.export LIFEFORM.DASH.ACCEL

.def LIFEFORM.PUNCH.AGE 6
.def LIFEFORM.PUNCH.ATTACK_DELAY 2

.def LIFEFORM.JUMPKICK.AGE 10

.def LIFEFORM.UPPERCUT.AGE 30
.def LIFEFORM.UPPERCUT.ATTACK_DELAY 27
.def LIFEFORM.UPPERCUT.IMPULSE -200
.def LIFEFORM.UPPERCUT.ACCEL -150

.def LIFEFORM.GRAB.AGE 15
.def LIFEFORM.THROW.AGE 20
.export LIFEFORM.THROW.AGE

.def LIFEFORM.COMBO.TIMEOUT 20
.export LIFEFORM.COMBO.TIMEOUT
.def LIFEFORM.COMBO.SATURATE 3
.export LIFEFORM.COMBO.SATURATE

.def LIFEFORM.STASH.AGE 20
.export LIFEFORM.STASH.AGE

.def LIFEFORM.SUPERPUNCH.IMPULSE 1400
.def LIFEFORM.SUPERPUNCH.ACCEL 80
.def LIFEFORM.SUPERPUNCH.AGE 28
.def LIFEFORM.SUPERPUNCH.ATTACK_DELAY 26


.def LIFEFORM.FRICTION.GROUND $ffff
.def LIFEFORM.FRICTION.AIR 50
.def LIFEFORM.FRICTION.ICE 5
.def LIFEFORM.FRICTION.SNOW 30
.def LIFEFORM.FRICTION.DASH 120
.def LIFEFORM.FRICTION.BOUNCE 10

.def LIFEFORM.TILE.BOUNDARY.DISTANCE 8

.def LIFEFORM.CARRY.START.X 8
.def LIFEFORM.CARRY.START.Y -8

.def LIFEFORM.CARRY.END.X -10
.def LIFEFORM.CARRY.END.Y -20

.def LIFEFORM.SPEED.MAX $3ff

.export LIFEFORM.CARRY.START.X
.export LIFEFORM.CARRY.START.Y
.export LIFEFORM.CARRY.END.X 
.export LIFEFORM.CARRY.END.Y

.def LIFEFORM.SUICIDE.AGE 160
.export LIFEFORM.SUICIDE.AGE
.def LIFEFORM.SUICIDE.DIALOGUE.AGE 130

.def LIFEFORM.MAX_HITS.PUNCH 2
.def LIFEFORM.MAX_HITS.KICK 3
.def LIFEFORM.MAX_HITS.DASH 4
.def LIFEFORM.MAX_HITS.THROWN 5
.def LIFEFORM.MAX_HITS.SLIDE 7
.def LIFEFORM.MAX_HITS.UPPERCUT 8
.def LIFEFORM.MAX_HITS.KNOCKOUT 10

.export LIFEFORM.MAX_HITS.THROWN

.enum 0 export
  LIFEFORM.TILE.BOUNDARY.GROUNDED dw
  LIFEFORM.TILE.BOUNDARY.AIRBORNE dw
  LIFEFORM.TILE.BOUNDARY.ETHEREAL dw
  LIFEFORM.TILE.BOUNDARY.FLYING dw
  LIFEFORM.TILE.BOUNDARY.DASHING dw
  LIFEFORM.TILE.BOUNDARY.BOUNCING dw
.ende


;zp-vars
.enum 0
  iterator INSTANCEOF iteratorStruct
  dimension INSTANCEOF dimensionStruct
  animation INSTANCEOF animationStruct
  oam INSTANCEOF oamStruct
  lifeform INSTANCEOF lifeformStruct
  zpLen ds 0
.ende

.base BSL
.bank BANK.PROGRAM_EXT
