.include "src/config/config.inc"

.def REGION.VIDEOMODE.THRESHOLD $0400
.def REGION.VIDEO.REFRESH.PAL 50
.def REGION.VIDEO.REFRESH.NTSC 60

.export REGION.VIDEO.REFRESH.PAL
.export REGION.VIDEO.REFRESH.NTSC

.base BSL
.bank BANK.PROGRAM
