.include "src/config/config.inc"

;defines

.def SCREEN.MOVE.THRESHOLD = 4

.def SCREEN.SEMI_IMMEDIATE.THRESHOLD 256

.def SCREEN.DIRECTION.OFFSET 40

.enum 0 export
  SCREEN.BOUNDARY.DIRECT db
  SCREEN.BOUNDARY.GROUNDED db
  SCREEN.BOUNDARY.AIRBORNE db
.ende

;ram buffers
.ramsection "global dmafifo vars" bank 0 slot 1
SCREEN.GLOBAL.START ds 0

GLOBAL.screen.position.x ds 3
GLOBAL.screen.position.y ds 3
GLOBAL.screen.size.x dw
GLOBAL.screen.size.y dw
GLOBAL.screen.min.x dw 
GLOBAL.screen.min.y dw
GLOBAL.screen.max.x dw  ;max value taking screen size into account
GLOBAL.screen.max.y dw
GLOBAL.screen.playfield.size.x dw   ;actual size of playfield (used for other objects to check their position). This is a global state hack, but whatever...
GLOBAL.screen.playfield.size.y dw
GLOBAL.screen.target.x dw
GLOBAL.screen.target.y dw
GLOBAL.screen.focussedObject ds 4
GLOBAL.screen.shake.offset.x dw
GLOBAL.screen.mode dw
GLOBAL.screen.direction dw
GLOBAL.screen.position.right.x dw ;contains position+size for faster onscreen checking
GLOBAL.screen.position.bottom.y dw

SCREEN.GLOBAL.END ds 0
.ends

.base BSL
.bank BANK.DATA

.def SPRITE.DEFAULT.SPEED $200

.section "math.luts" superfree
core.screen.move.airborne.lut:
  .dw 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
  .dw 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
  .dw 0,0,0,0,0,0,0,0,0

core.screen.move.lut:
  .dw 0, 0, 0, 0, 0
  .dw SPRITE.DEFAULT.SPEED/16,SPRITE.DEFAULT.SPEED/16,SPRITE.DEFAULT.SPEED/16,SPRITE.DEFAULT.SPEED/16
  .dw SPRITE.DEFAULT.SPEED/8,SPRITE.DEFAULT.SPEED/8,SPRITE.DEFAULT.SPEED/8,SPRITE.DEFAULT.SPEED/8
  .dw SPRITE.DEFAULT.SPEED/4,SPRITE.DEFAULT.SPEED/4,SPRITE.DEFAULT.SPEED/4,SPRITE.DEFAULT.SPEED/4
  .dw SPRITE.DEFAULT.SPEED,SPRITE.DEFAULT.SPEED,SPRITE.DEFAULT.SPEED,SPRITE.DEFAULT.SPEED,SPRITE.DEFAULT.SPEED,SPRITE.DEFAULT.SPEED,SPRITE.DEFAULT.SPEED
  .dw SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2
  .dw SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2
  .dw SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2
  .dw SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2
  .dw SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2,SPRITE.DEFAULT.SPEED*2
  .dw SPRITE.DEFAULT.SPEED*3,SPRITE.DEFAULT.SPEED*3,SPRITE.DEFAULT.SPEED*3,SPRITE.DEFAULT.SPEED*3,SPRITE.DEFAULT.SPEED*3,SPRITE.DEFAULT.SPEED*3
  .dw SPRITE.DEFAULT.SPEED*4-1,SPRITE.DEFAULT.SPEED*4-1
core.screen.move.lut.end:

.ends

.base BSL
.bank BANK.PROGRAM
