/**
* Cutscene anticipating final boss
*
*/

  SCRIPT finalOnslaught

  .redef obj.script.slave hashPtr.1

  .redef obj.hud this._tmp
  
	SET_CUTSCENE_OPTIONAL

  HUD_DISABLE obj.hud
  SCRIPT_NEW Script.CLS.PTR obj.script.slave textbox text.dialogue.readyFinalOnslaught FALSE
  WAIT_FOR obj.script.slave

  SCRIPT_NEW Script.CLS.PTR obj.script.slave textbox text.dialogue.almostThere FALSE
  WAIT_FOR obj.script.slave
  HUD_ENABLE obj.hud

  DIE